---
version: build-{build}
environment:
  matrix:
  - TARGET: x86_64-pc-windows-gnu
    BITS: 64
    MSYS2: 1
  - TARGET: i686-pc-windows-gnu
    BITS: 32
    MSYS: 1
install:
    # install OpenSSL
  - ps: Start-FileDownload "http://slproweb.com/download/Win${env:BITS}OpenSSL-1_1_0f.exe"
  - Win%BITS%OpenSSL-1_1_0f.exe /SILENT /VERYSILENT /SP- /DIR="C:\OpenSSL"
  - appveyor DownloadFile https://curl.haxx.se/ca/cacert.pem -FileName C:\OpenSSL\cacert.pem

  # Install Rust
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - rustc -V
  - cargo -V
build: off
test_script:
  # Compile, run test, check if the binary works, build release binaries
  - cargo test
  - cargo run -- --help
  - cargo build --release

