---
version: build-{build}
environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
    VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: x86_64-pc-windows-msvc
    ARCH: amd64
    VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
    VS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: i686-pc-windows-msvc
    ARCH: x86
    VS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: x86_64-pc-windows-gnu
    MSYS_BITS: 64
    OPENSSL: C:\OpenSSL-Win32
  - TARGET: i686-pc-windows-gnu
    MSYS_BITS: 32
    OPENSSL: C:\OpenSSL-Win32
install:
  - SET OPENSSL_INCLUDE_DIR=%OPENSSL%\include
  - SET OPENSSL_LIB_DIR=%OPENSSL%\bin
  - CP %OPENSSL%\bin\ssleay32.dll %OPENSSL%\bin\libssl32.dll
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.18.0-${env:TARGET}.exe" -FileName "rust-stable.exe"
  - rust-stable.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - if defined VS call "%VS%" %ARCH%
  - set PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - if defined MSYS_BITS set PATH=%PATH%;C:\msys64\mingw%MSYS_BITS%\bin
  - rustc -V
  - cargo -V
build: off
test_script:
  # Compile, run test, check if the binary works, build release binaries
  - cargo test
  - cargo run -- --help
  - cargo build --release

